### ISSUE TITLE
Nodejs deprecation: MakeCallback with domain property

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1475] opened 2019-09-02 06:09 UTC
DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.

Needs to be fixed so we can update the node stack.

**Comment by chris-lawton** [comment] 2019-09-09 09:22
@frjo - what are the steps to reproduce this?

**Comment by frjo** [comment] 2019-09-09 09:55
@chris-lawton 

```
rm -rf node_modules
rm package-lock.json
npm install
gulp watch:app and/or gulp app:production
```

When I run this now I get more errors:

```
(node:40755) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
Unhandled rejection Error in plugin "webpack-stream"
Message:
    ./src/containers/StatusActions.js
Module Error (from /Users/frjo/Sites/otf/node_modules/eslint-loader/index.js):

/Users/frjo/Sites/otf/opentech/static_src/src/app/src/containers/StatusActions.js
  103:24  error  'submission.executionActionError' is missing in props validation  react/prop-types

✖ 1 problem (1 error, 0 warnings)

 @ ./src/containers/DisplayPanel/index.js 40:0-54 93:26-39
 @ ./src/components/DetailView/index.js
 @ ./src/containers/GroupByStatusDetailView.js
 @ ./src/SubmissionsByRoundApp.js
 @ ./src/submissionsByRoundIndex.js
 @ multi @babel/polyfill ./src/submissionsByRoundIndex

[11:51:29] The following tasks did not complete: app:production
[11:51:29] Did you forget to signal async completion?
```

When you get something working with npm you do not want to touch it but then there are security alerts and you need to…

**Comment by chris-lawton** [comment] 2019-09-09 10:40
That looks like two issues, one regarding the deprecation of `MakeCallback` and one regarding the missing `PropTypes`.

For clarity i've opened a separate issue and PR for `PropTypes` here https://github.com/OpenTechFund/opentech.fund/issues/1498 leaving this for `MakeCallback`. 

With regards to that I'm currently unsure what's causing it.

**Comment by vaibhavmule** [comment] 2020-03-08 12:01
I wasn't able to figure out this, I tried trace deprecation using `process.traceDeprecation = true;`
I didn't get exact trace from which package or file it is causing the deprecation warning.

```
(node:2729) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
    at emitMakeCallbackDeprecation (domain.js:111:13)
    at process.topLevelDomainCallback (domain.js:122:5)

```

**Comment by frjo** [comment] 2020-03-11 10:49
Lets wait and see for this then. Hopefully it will go away when one of the packages we are using is updated.

Thanks for looking at it and adding good links.

**Comment by vimal1083** [comment] 2020-08-24 16:41
Unable to reproduce this issue, Shall we close this one ?

**Closed** 2020-08-25 04:17 UTC
Labels: bug, priority, react
