### ISSUE TITLE
Application Detail Page: Create project from accepted submission

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1325] opened 2019-07-25 08:02 UTC
- [x] From an accepted submission I can create a new project 
- [x] If a project exists I am unable to create another project for that submission 
- [x] Slack message is sent when a project is created 
- [x] QA is complete

**Comment by abigail-hampson** [comment] 2019-08-05 14:30
Looks good to me, can go onto test if QA is all complete

**Comment by abigail-hampson** [comment] 2019-08-07 15:03
Hello, 

This is now ready for testing against the acceptance criteria above, you can test this by going to an accepted submission and using the create a project button on the right. 
Let me know if you have any questions. 

Thanks,
Abigail

**Comment by fourthletter** [comment] 2019-08-09 15:54
Acceptance criteria were visible and functional during test. Thanks! 🔥

What does the last bit "QA is complete" mean?

**Comment by todd-dembrey** [comment] 2019-08-12 13:02
@fourthletter That is our internal QA checks before it gets to you (we've written tests, reviewed it, tested it on dev etc)

**Comment by saoun** [comment] 2019-08-15 23:38
Have an error on my end, but not sure what's going on. My workflow:
- I go to a submission
- Create a project
- Page is now updated with the project linked to that submission, on the right handside of the page
- I click on the project link, and I get an server error

The server error comes up for some, and not for others. Is that expected behavior at this point of testing?

**Comment by fourthletter** [comment] 2019-08-22 13:45
@saoun Torchbox proposed a fix to the issue you're referring to here #1327 and here #1403

**Comment by saoun** [comment] 2020-01-15 17:46
@abigail-hampson is this done? can we close?

**Comment by saoun** [comment] 2020-04-07 01:19
@abigail-hampson what's the status on this ?

**Comment by todd-dembrey** [comment] 2020-04-27 16:13
The work referenced by this ticket has been merged and deployed.

The issue you mentioned is likely the issue fixed in #1540 due to its inconsistent nature.

Please open a new bug report if this is still an issue.

**Closed by todd-dembrey** 2020-04-27 16:13 UTC
Labels: For TBX, Sprint 1 🏃
