### ISSUE TITLE
Can't add partners in a mobile browser (Chrome + Android 10)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1273] opened 2019-06-20 18:54 UTC
**Describe the bug**
Can't add partners in a mobile browser (Chrome + Android 10)

**To Reproduce**
1. Go to submission: https://apply.opentech.fund/apply/submissions/4620/
2. Hit partner button
3. Try to expand list of partners, nothing happens

**Expected behavior**
When I click the expand partners list that list would expand out and I can chose them like the other similar functions. This works fine when I try via desktop browser.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Comment by frjo** [comment] 2019-06-20 19:45
@danblah Is the Reviewer widget working or has it the same problem?

**Comment by danblah** [comment] 2019-06-20 20:08
Reviewer widget does work.

**Comment by danblah** [comment] 2019-06-21 00:44
Correction, reviewers does not work but lead does. Also doesn't work when requesting the desktop version from a mobile browser.

**Comment by frjo** [comment] 2019-06-21 04:42
There is no desktop/mobil version. Just the one site with css media queries. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment] 2020-03-13 09:52
Duplicate of #1758

**Closed by frjo** 2020-03-13 09:52 UTC
Labels: bug
