### ISSUE TITLE
Project detail view: Action send to Approver (Director)

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1332] opened 2019-07-25 08:12 UTC
- Select user 
- Add 'director' **NB: Should consider a more generic term here "Director" is potentially OTF specific**

- [x] Users can be added to the director group (this is a new group) 
- [x] Send for approval link opens a modal to confirm action
- [x] Slack message confirmation to the all directors notifying them the project is await approval
- [x] Activity logged for the event
- [x] UI of project page updated to prevent edits while it is in approval 
- [x] Once sent for approval you cannot send for approval again 
- [x] QA complete

**Comment by abigail-hampson** [comment] 2019-08-13 11:47
Looks good to me

**Comment by abigail-hampson** [comment] 2019-08-29 20:54
This is now ready to be tested against the acceptance criteria. Users can be added into the approver role in the wagtail admin (https://test-apply.opentech.fund/admin/users/), on a project page you can then send to an approver and choose who this will be. Thanks!

**Comment by fourthletter** [comment] 2019-09-09 16:43
All acceptance criteria were visible and functional during test. Test was smooth as milk in the milky way. The only missing aspect was **slack message confirmation**. 

[ ] Slack message confirmation to the all directors notifying them the project is await approval was NOT visible and functional during test.

**Comment by todd-dembrey** [comment] 2019-10-03 14:59
> [ ] Slack message confirmation to the all directors notifying them the project is await approval was NOT visible and functional during test.

This was most likely due to the approver not having a slack ID set - they cannot be messaged if there is no id.  

This change will be deployed to master - but it would be worth you retesting this @fourthletter so that we are happy with this.

**Comment by fourthletter** [comment] 2019-11-21 14:26
All acceptance criteria were visible and functional during test. Thanks! 💥 

A slack message did NOT appear on the webapp test channel, but this is fine.

**Comment by saoun** [comment] 2020-01-15 19:12
hey @todd-dembrey @fourthletter, what is the update on this? are we still on the slack message?

**Comment by todd-dembrey** [comment] 2020-04-27 16:52
I've confirmed that the slack message is sent. 
![image](https://user-images.githubusercontent.com/6338661/80398607-cbea3680-88af-11ea-991f-ff53cf52a144.png)

This is merged and deployed.

**Closed by todd-dembrey** 2020-04-27 16:52 UTC
Labels: For TBX, Sprint 1 🏃
